language: php

php:
  - 7.3
  - 7.4
  - 8.0

env:
  global:
    - DEFAULT_COMPOSER_FLAGS="--no-interaction --no-ansi --no-progress --no-suggest --prefer-dist"

matrix:
  include:
    - php: 7.3
      env: SYMFONY_VERSION=v4
    - php: 7.4
      env: SYMFONY_VERSION=v4
    - php: 7.4
      env: SYMFONY_VERSION=v5
    - php: 8.0
      env: SYMFONY_VERSION=v4
    - php: 8.0
      env: SYMFONY_VERSION=v5

before_install: composer self-update

install:
  - composer require dunglas/symfony-lock:${SYMFONY_VERSION} --no-update
  - composer install --prefer-source

script: vendor/bin/phpunit tests

cache:
  directories:
    - $HOME/.composer/cache/files